project:
  type: website

website:
  title: "Katherine Higgs"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com/in/katherine-amelia-higgs
      - icon: github
        href: https://github.com/
      
format:
  html:
    theme: pulse
    css: styles.css

editor: visual

