project:
  type: website
  output-dir: docs
  
website:
  title: "Katherine Higgs"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://linkedin.com/in/katherine-amelia-higgs
      - icon: github
        href: https://github.com/katherinehiggs
      - text: '![](bluesky-logo.png){height=1em}'
        href: https://bsky.app/profile/katherinehiggs.bsky.social
      
format:
  html:
    theme: 
      - zephyr
      - styles.scss

editor: visual

